In [49]:
import torch
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))


In [50]:
print(x)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [51]:
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((x, y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [52]:
torch.cat((x, y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [53]:
# 通过比较来得到一个逻辑值张量
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [54]:
x.sum()

tensor(66.)

In [55]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1,2))
print(a, b)
# 广播机制，如果a和b同维度会自动扩展张量到同一个size进行计算
a + b

tensor([[0],
        [1],
        [2]]) tensor([[0, 1]])


tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [56]:
# 会自动开辟新的内存块
before = id(b)
b = a + b
id(b) == before

False

In [57]:
z = torch.zeros_like(y)
print("id(z):", id(z))
# 比较节省内存的写法
z[:] = x + y
print("id[z]:", id(z))

id(z): 2724044239712
id[z]: 2724044239712


In [58]:
# 只有当tensor中只存在一个元素才可以使用item()获取
a.item()

ValueError: only one element tensors can be converted to Python scalars

In [63]:
y[2][1] = 0
y[0][2:4] = 1
y2 = torch.ones((4,5))
print(y)
print(y2)
print(torch.mm(y, y2))
# y * y2

y3 = torch.ones((3,4))
a = torch.tensor([0,1,2,3])
b = torch.tensor([2,3,4,5])
# dot是向量的点积和
print(torch.dot(a, b))
# 乘法是相同位置上依次乘
print(a * b)

tensor([[2., 1., 1., 1.],
        [1., 2., 3., 4.],
        [4., 0., 2., 1.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[ 5.,  5.,  5.,  5.,  5.],
        [10., 10., 10., 10., 10.],
        [ 7.,  7.,  7.,  7.,  7.]])
tensor(26)
tensor([ 0,  3,  8, 15])
tensor([  0,   1,  16, 243])
