In [1]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [3]:
# 如果需要梯度，等价于x = torch.arange(4.0, requires_grad=True)
x.requires_grad_(True)
print(x.grad)

None


In [4]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [5]:
# 求导并反向传播
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [6]:
x.grad == 4 * x

tensor([True, True, True, True])

In [7]:
# 清除梯度
x.grad.zero_()
y = x.sum()

In [8]:
print(y)

tensor(6., grad_fn=<SumBackward0>)


In [9]:
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [10]:
# 将某些计算移动到记录的计算图之外
x.grad.zero_()
y = x * x
# detach代表把y当作一个常数而不是x的函数，如此以来u对于系统来说就是一个常数
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])