In [1]:
import torch
from torch import nn
from torch.nn import functional as F

x = torch.arange(4)
# 将矩阵保存到文件中
torch.save(x, 'x-file')

In [5]:
# 从文件中读
x2 = torch.load('x-file')
x2.data, x2

(tensor([0, 1, 2, 3]), tensor([0, 1, 2, 3]))

In [6]:
y = torch.zeros(4)
torch.save([x, y],'x-files')
x2, y2 = torch.load('x-files')
(x2, y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [7]:
# 保存从字符串映射到张量的字典
mydict = {'x': x, 'y': y}
torch.save(mydict, 'mydict')
mydict2 = torch.load('mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

### 加载和保存模型

In [8]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)

    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))

net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)

In [10]:
# 通过state_dict()取出网络的所有的参数
torch.save(net.state_dict(), 'mlp.params')

In [13]:
# 读取还原出网络

# 首先要实例化出网络
clone = MLP()
clone.load_state_dict(torch.load("mlp.params"))
clone

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [14]:
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])