In [2]:
import torch
import numpy as np
from typing import Optional, Union

In [3]:
def generate_original_PE(length: int, d_model: int) -> torch.Tensor:
    """Generate positional encoding as described in original paper.  :class:`torch.Tensor`
    Parameters
    ----------
    length:
        Time window length, i.e. K.
    d_model:
        Dimension of the model vector.
    Returns
    -------
        Tensor of shape (K, d_model).
    """
    PE = torch.zeros((length, d_model))

    pos = torch.arange(length).unsqueeze(1)
    PE[:, 0::2] = torch.sin(
        pos / torch.pow(1000, torch.arange(0, d_model, 2, dtype=torch.float32)/d_model))
    PE[:, 1::2] = torch.cos(
        pos / torch.pow(1000, torch.arange(1, d_model, 2, dtype=torch.float32)/d_model))

    return PE

In [4]:
def generate_regular_PE(length: int, d_model: int, period: Optional[int] = 24) -> torch.Tensor:
    """Generate positional encoding with a given period.
    Parameters
    ----------
    length:
        Time window length, i.e. K.
    d_model:
        Dimension of the model vector.
    period:
        Size of the pattern to repeat.
        Default is 24.
    Returns
    -------
        Tensor of shape (K, d_model).
    """
    PE = torch.zeros((length, d_model))

    pos = torch.arange(length, dtype=torch.float32).unsqueeze(1)
    PE = torch.sin(pos * 2 * np.pi / period)
    PE = PE.repeat((1, d_model))

    return PE

In [5]:
generate_original_PE(100,10)

tensor([[ 0.0000,  1.0000,  0.0000,  1.0000,  0.0000,  1.0000,  0.0000,  1.0000,
          0.0000,  1.0000],
        [ 0.8415,  0.8770,  0.2486,  0.9921,  0.0631,  0.9995,  0.0158,  1.0000,
          0.0040,  1.0000],
        [ 0.9093,  0.5383,  0.4815,  0.9685,  0.1259,  0.9980,  0.0317,  0.9999,
          0.0080,  1.0000],
        [ 0.1411,  0.0672,  0.6842,  0.9295,  0.1882,  0.9955,  0.0475,  0.9997,
          0.0119,  1.0000],
        [-0.7568, -0.4205,  0.8440,  0.8759,  0.2497,  0.9920,  0.0634,  0.9995,
          0.0159,  1.0000],
        [-0.9589, -0.8047,  0.9508,  0.8083,  0.3103,  0.9875,  0.0792,  0.9992,
          0.0199,  1.0000],
        [-0.2794, -0.9910,  0.9980,  0.7280,  0.3696,  0.9821,  0.0950,  0.9989,
          0.0239,  0.9999],
        [ 0.6570, -0.9335,  0.9825,  0.6362,  0.4274,  0.9756,  0.1107,  0.9985,
          0.0279,  0.9999],
        [ 0.9894, -0.6464,  0.9053,  0.5343,  0.4836,  0.9682,  0.1265,  0.9980,
          0.0318,  0.9999],
        [ 0.4121, -

In [17]:
import torch.nn as nn

In [19]:
base_loss = nn.MSELoss()

In [26]:
pred = torch.rand((2,3,4))

In [27]:
true = torch.rand((2,3,4))

In [28]:
base_loss(pred[..., -1], true[..., -1])

tensor(0.2435)

In [29]:
print(pred)

tensor([[[0.7966, 0.7702, 0.2129, 0.6237],
         [0.7851, 0.7887, 0.9495, 0.5214],
         [0.0679, 0.4628, 0.8679, 0.9468]],

        [[0.3977, 0.1242, 0.2867, 0.4272],
         [0.3226, 0.6133, 0.0471, 0.6711],
         [0.7556, 0.8902, 0.2054, 0.7452]]])


In [31]:
print(pred[..., :-1])

tensor([[[0.7966, 0.7702, 0.2129],
         [0.7851, 0.7887, 0.9495],
         [0.0679, 0.4628, 0.8679]],

        [[0.3977, 0.1242, 0.2867],
         [0.3226, 0.6133, 0.0471],
         [0.7556, 0.8902, 0.2054]]])


In [32]:
print(pred[..., -1])

tensor([[0.6237, 0.5214, 0.9468],
        [0.4272, 0.6711, 0.7452]])


In [36]:
a = torch.rand(2,2)

In [37]:
print(a)

tensor([[0.2217, 0.1642],
        [0.0135, 0.9929]])


In [38]:
print(a[0])

tensor([0.2217, 0.1642])


tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
(tensor([[[1, 2]],

        [[5, 6]]]), tensor([[[3, 4]],

        [[7, 8]]]))


(tensor([[[1, 2]],

        [[5, 6]]]), tensor([[[3, 4]],

        [[7, 8]]]))
